# Generated by Django 3.1.7 on 2021-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210418_1201'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_ids',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
